### ISSUE TITLE
Use `CONSOLIDATION_REQUEST_PREDEPLOY_CODE` from `alloy_eips` once correct bytecode is included

### ISSUE THREAD

**Issue by Evalir** [init4tech/trevm#20]
Once https://github.com/alloy-rs/alloy/issues/1103 is resolved, we should instead use the constant included in `alloy_eips::eip7251` instead of having our own defined in tests.

**Comment by Evalir** [comment]
fix introduced in https://github.com/alloy-rs/alloy/pull/1105, now just need a release and we can remove this.

**Comment by prestwich** [comment]
this is done 🫡
