### ISSUE TITLE
Feature request: no-std

### ISSUE THREAD

**Issue by roninjin10** [init4tech/trevm#39]
I'm wondering following questions:

- Could trevm become no-std
- Does trevm plan on becoming no-std or would it accept contributions to start moving in that direction?
- How big of a lift is making it no-std?

The use case would be using trevm compiled to wasm

**Comment by prestwich** [comment]
given that revm supports no-std via the std feature, we could almost definitely support it in trevm. We don't have current plans, but would accept contributions moving in that direction

Note that the typestate API likely would not work well with something like wasm-bindgen

**Comment by Evalir** [comment]
Hey @roninjin10 — we just merged no-std support. Would love for you to try it out whenever you like!

**Comment by roninjin10** [comment]
Let's go!
